import "@/styles/globals.css";

import type { Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create T3 App",
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => (
  <html className={geist.variable} lang="en">
    <body>
      <TRPCReactProvider>{children}</TRPCReactProvider>
    </body>
  </html>
);

export default RootLayout;
