import "@/styles/globals.css";

import type { Metadata } from "next";

import { GeistSans } from "geist/font/sans";

export const metadata: Metadata = {
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create T3 App",
};

const Layout = ({
  children,
}: Readonly<{ children: React.ReactNode }>): React.JSX.Element => {
  return (
    <html className={`${GeistSans.variable}`} lang="en">
      <body>{children}</body>
    </html>
  );
};

export default Layout;
