import "@/styles/globals.css";

import type { Metadata } from "next";

import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";

import { cn } from "@/lib/utils";
import { varelaRound } from "@/styles/fonts";

export const metadata: Metadata = {
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
  title: "Create T3 App",
};

const Layout = ({
  children,
}: Readonly<{ children: React.ReactNode }>): React.JSX.Element => {
  return (
    <ClerkProvider>
      <html
        className={cn(
          "font-varela-round min-h-svh antialiased",
          varelaRound.variable,
        )}
        lang="en"
      >
        <body>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          <SignedIn>
            <UserButton />
          </SignedIn>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
};

export default Layout;
